### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by bmw95** [bmw95/all-about-trees#1]
- [ ] Change TreeModule to something else

- [ ] Add tests using Minitest::UnitTest

- [ ] Fix the loop on 159 such that the value does not have to be checked once again after the loop finishes. 

- [ ] When the user inputs "n" to search_all and the program comes across the first instance of the matching value, it does not reset the deleted_items array or @branch. Only on search_all == true does it do this.

- [ ] Delete most of the comments. Create ones which describe the input and output of methods. No more, unless explicitly needed.
